frase = input("Digite algo: ")
print("O tipo primitivo desse número é", type(frase))
print("Só tem espaços?", frase.isspace())
print("É um número? ", frase.isnumeric())
print("É alfabético? ", frase.isalpha())
print("É alfanumérico? ", frase.isalnum())
print("Está em minusculas?" , frase.islower())
print("Está em maiuscula", frase.isupper())
print("Está capitalizada?", frase.istitle())